spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/liquibase_example
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: password
    change-log: classpath:resources/db/changelog/db.changelog-master.yaml